---
title: "02_patchformation"
author: "Casey Menick"
date: "`r Sys.Date()`"
output: html_document
---


```{r packages, message=FALSE, warning=FALSE}
library(tidyverse)
library(terra)
library(patchwoRk)
library(sf)
library(mapview)
library(exactextractr)
```

```{r}
rast_list <- list.files(path = "data/highsev", pattern='.tif', all.files=TRUE, full.names=TRUE)
rast_all <- lapply(rast_list, rast)
# names(rast_all) <- str_c(rast_list)
rast_collection <- sprc(rast_all)

crs <- crs(rast_collection[1])
```


```{r data import, show_col_types = FALSE}
fires_select <- st_read("output/fires_select.shp")%>% 
  st_transform(., crs=crs) %>% 
  filter(year %in% c(1988,1989,1990,1991))

fires_export <- st_read("output/fires_export.shp")%>% 
  st_transform(., crs=crs)

conus_forestgroup <- raster('data/conus_forestgroup.tif')
forest_codes <- read_csv('data/forestgroupcodes.csv')
```

```{r patchmorph, message=FALSE, warning=FALSE}
# loop through RdNBR rasters, assign >640 to high severity category
# utilize patchmorph to act as 3x3 cell majority filter
patch_df <- list()
for (i in 1:length(rast_all)){
  rast_fire <- raster(rast_collection[i])
  rast_fire[rast_fire < 640] <- 0
  rast_fire[rast_fire > 640] <- 1

  patch <- patchMorph(rast_fire, spurThresh = 3, gapThresh = 3)
  patch_poly <- as.polygons(rast(patch)) %>%
    st_as_sf()
  df_union_cast <- patch_poly %>%
    st_cast(., "POLYGON") %>%
    filter(layer == 1)
  patch_df[[i]] <- df_union_cast}

patch_poly_all <- do.call(rbind,patch_df)
```

```{r message=FALSE, warning=FALSE}
patches_full <- patch_poly_all %>% 
  st_transform(., crs=crs) %>% 
  mutate(patch_area_ha = as.numeric(st_area(.)/10000)) %>%
  filter(patch_area_ha > 2.25)
  
highsev_info <- patches_full%>% 
  st_join(.,fires_select,join = st_intersects,left= FALSE,largest = TRUE)%>% 
  dplyr::select("fire_nm","Evnt_ID","year","patch_area_ha")
  
highsev_patches <- left_join(highsev_info,exact_extract(conus_forestgroup,highsev_info, 'mode', append_cols = TRUE, max_cells_in_memory = 3e+08)) %>% 
  mutate(fire_foresttype = case_when(mode==200 ~ "Douglas-Fir",
                                     mode==220 ~ "Ponderosa",
                                     mode==260 ~ "Fir-Spruce",
                                     mode==280 ~ "Lodegepole Pine",
                                     mode==0 ~ "Unforested",
                                     TRUE ~ "Other"))
```


```{r export, message=FALSE, warning=FALSE}
# st_write(highsev_patches, "output/", "highsev_patches_final.shp",driver = 'ESRI Shapefile')
# st_write(patch_poly_all, "output/", "highsev_patches_morph_unfiltered.shp",driver = 'ESRI Shapefile')
```


```{r}
training_datapoints <- st_read("output/training_datapoints.shp")%>% 
  st_transform(., crs=crs(highsev_patches)) 
quadrants_fullset <- st_read("output/quadrants_fullset.shp")%>% 
  st_transform(., crs=crs(highsev_patches)) 
training_squarebuffer <- st_read("output/training_data_squarebuffer.shp")%>% 
  st_transform(., crs=crs(highsev_patches)) 

st_write(training_datapoints, "output/", "training_datapoints_proj",driver = 'ESRI Shapefile')
st_write(quadrants_fullset, "output/", "quadrants_fullset_proj",driver = 'ESRI Shapefile')
st_write(training_squarebuffer, "output/", "training_squarebuffer",driver = 'ESRI Shapefile')
```

