---
title: "03_samplingpoints"
author: "Casey Menick"
date: "`r Sys.Date()`"
output: html_document
---


```{r message=FALSE, warning=FALSE}
library(elevatr)
library(tidyverse)
library(sf)
library(terra)
library(mapview)
```

```{r message=FALSE, warning=FALSE}
# data
fires_select <- st_read("output/fires_select.shp")%>% 
  filter(year %in% c(1988,1989,1990,1991))
fires_export <- st_read("output/fires_export.shp")
patches <- st_read("output/highsev_patches_final.shp") %>% 
  st_transform(crs=crs(fires_export))
```

```{r message=FALSE, warning=FALSE}
fire_list <- unique(patches$Evnt_ID)

quadrants_df = list()

for(i in fire_list){
  
  patch_fire <- patches %>% 
    filter(Evnt_ID == i)
  
  Evnt_ID <- i
  
  # get exterior/interior
  patches_interior <- st_buffer(patch_fire,-90)
  patches_exterior <- do.call(rbind,
                              purrr::map(1:nrow(patch_fire), ~st_difference(patch_fire[.x,], patches_interior[.x,]))) %>% 
    select(colnames(patches_interior))

  # get elevation/ ccaspect
  dem <- get_elev_raster(patch_fire,z=10)
  aspect <- terrain(dem, opt = "aspect",unit = "radians")
  ccaspect <- cos(aspect)

  ccaspect[ccaspect>0] <- 1
  ccaspect[ccaspect<0] <- -1
  ccaspect_poly <- as.polygons(rast(ccaspect)) %>%
    st_as_sf()
  
  pos_aspect <- ccaspect_poly %>%
    filter(layer==1)
  neg_aspect <- ccaspect_poly %>%
    filter(layer==-1)

  # get quadrants
  pos_ext <- st_intersection(pos_aspect,patches_exterior)%>% 
    st_transform(crs=crs(fires_export)) %>% 
    st_union() %>% 
    st_as_sf()%>% 
    mutate(quadrant = "pos_ext",
           Evnt_ID = i,
           quad_id = paste0(Evnt_ID,"-",quadrant))
  
  pos_int <- st_intersection(pos_aspect,patches_interior)%>% 
    st_transform(crs=crs(fires_export)) %>% 
    st_union() %>% 
    st_as_sf()%>% 
    mutate(quadrant = "pos_int",
           Evnt_ID = i,
           quad_id = paste0(Evnt_ID,"-",quadrant))
  
  neg_ext <- st_intersection(neg_aspect,patches_exterior)%>% 
  st_transform(crs=crs(fires_export)) %>% 
  st_union() %>% 
  st_as_sf()%>% 
  mutate(quadrant = "neg_ext",
         Evnt_ID = i,
         quad_id = paste0(Evnt_ID,"-",quadrant))
  
  neg_int <- st_intersection(neg_aspect,patches_interior)%>% 
  st_transform(crs=crs(fires_export)) %>% 
  st_union() %>% 
  st_as_sf()%>% 
  mutate(quadrant = "neg_int",
         Evnt_ID = i,
         quad_id = paste0(Evnt_ID,"-",quadrant))
  
  #combine, export quadrants
  all_quadrants <- rbind(neg_int,pos_int,neg_ext,pos_ext)
  
  quadrants_df[[i]] <- all_quadrants
}

quadrants_fullset <- do.call(rbind,quadrants_df) %>% 
  st_as_sf() 
```

```{r}
#st_write(fires_export, "output/", "fires_export.shp",driver = 'ESRI Shapefile')
quad_export <- quadrants_fullset %>% 
  st_transform(crs=crs(fires_export))

st_write(quadrants_fullset,"output/","quadrants_fullset.shp",driver = "ESRI Shapefile")
crs(quadrants_fullset)
```
```{r}
points <- st_read("data/points_dataset_uptofire1.shp")

mapview(list(points,patches))

```

