---
title: "05_model"
author: "Casey Menick"
date: "`r Sys.Date()`"
output: html_document
---

```{r libraries, message=FALSE, warning=FALSE}
library(mapview)
library(sf)
library(terra)
library(tidyverse)
library(ggplot2)
library(car)
library(forcats)
```

```{r}
# bring in snow-on landsat imagery tiles, merge into collection
rast_list <- list.files(path = "data/landsat", pattern='.tif', all.files=TRUE, full.names=TRUE)
rast_all <- lapply(rast_list, rast)
rast_collection <- sprc(rast_all)

crs <- crs(rast_collection[1])
```

```{r}
# bring in training points
points <- st_read("data/points/points_export.shp") %>% 
  st_transform(crs=crs)
```


```{r}
# extract landsat values to each training point
extracted_df <- list()
for(i in 1:length(rast_all)){
  print(i)
  extracted_points <- st_as_sf(terra::extract(rast_collection[i], points,bind = TRUE))
  extracted_df[[i]] <- extracted_points 
}

training_dataset <- do.call(rbind,extracted_df) %>% drop_na()%>% 
  mutate(absence = case_when(class == "absence" ~ "absence",
                             TRUE ~ "presence"),
         class = as.factor(class),
         absence = as.factor(absence),
         class = fct_relevel(class,c("absence","presencetrace","presence1to10"))) %>% 
  rename(f_type = ptch_fr,
         area_ha = ptch_r_) %>% 
  st_drop_geometry() %>% 
  select(-pixel_qa,-qd_vnt_,-qd_fr_d) %>% 
  drop_na()
```

```{r}
pres_abs_type <- training_dataset %>% 
  group_by(f_type,absence) %>% 
  summarize(n=n()) %>% 
  mutate(percent= 100*n/sum(n)) %>% 
  filter(absence=="presence")

pres_abs_type
```

```{r}
pres_abs_quad <- training_dataset %>% 
  group_by(quad,absence) %>% 
  summarize(n=n()) %>% 
  mutate(percent= 100*n/sum(n)) %>% 
  filter(absence=="presence")

pres_abs_quad
```

```{r}
ggplot(training_dataset,aes(class,ndvi)) +
  geom_boxplot()

ggplot(training_dataset %>% filter(class %in% c("absence","presencetrace")),aes(class,ndvi)) +
  geom_boxplot()+
  ylim(-.1,.1)

ggplot(training_dataset,aes(absence,ndvi)) +
  geom_boxplot()

# ggplot(training_dataset,aes(ndvi,ndfsi,color=absence)) +
#   geom_point()
#   
# ggplot(training_dataset,aes(ndvi,ndfsi,color=absence)) +
#   geom_density2d() 
```

```{r}
pairs(training_dataset %>% select("class","ndvi","savi","ndsi","ndfsi","nbr2"))


pairs(training_dataset %>% select("ndvi","ndfsi"),
      pch = c(16),
      col = c("red","dark green")[training_dataset$absence])
```

```{r}
cor(training_dataset %>% dplyr::select(-red,-green,-blue,-absence,-class,-f_type,-Evnt_ID,-evi,-quadrant)) 
```


```{r}
training_dataset <- training_dataset %>% 
  mutate(binom=case_when(absence=="absence"~0,
                         TRUE ~1),
         binom=as.factor(binom)) %>% 
  drop_na()

# add forest type, fire
lm_conifer <- glm(absence ~  ndvi +ndsi+nbr2, data = training_dataset, family = binomial(logit))

summary(lm_conifer)

vif(lm_conifer)
```


```{r}
image_subset <- mask(rast_collection[1],fires_select)
rast_predicted <- terra::predict(image_subset,lm_conifer, type="response", se.fit=TRUE)

library(raster)
mapview(raster(rast_predicted))
test<- as.data.frame(rast_predicted)
```
