# NDVI Trajectory

## Set Up

### Libraries 

```{r libraries6, message=FALSE, warning=FALSE}
library(ggplot2)
library(ggthemes)
library(tidyverse)
library(sf)
library(terra)
library(raster)
library(mapview)
library(exactextractr)
library(forcats)
library(broom)
library(knitr)
library(sjPlot)
```

### Import Fires

```{r patch and fire import, message=FALSE, warning=FALSE, results='hide'}
# import high-severity patches
patches <- st_read("data/patches/highsev_patches.shp") %>% 
  st_transform(crs="EPSG: 4326")

# set crs
crs <- crs(patches)

# import fire boundaries
fires_export <- st_read("data/fire_boundaries/fires_export.shp")%>% 
  st_transform(., crs=crs)
```

### Prepare Data for Bands and Fire Names

#### Bands
```{r band names, message=FALSE, warning=FALSE}
# list band names and years
bands <- c("blue", "green", "red", "nir", "swir1", "swir2", "ndvi", "ndwi", "nbr", "nbr2", "ndsi", "ndfsi", "evi")
years <- c(1984:2020)

# create list of all combinations of bands, in the appropriate order
bandnames <- list(bands,years) %>%
  cross() %>%
  map(lift(paste0))

bandlist <- do.call(rbind,bandnames)
```

#### Fire Names

```{r fire names, message=FALSE, warning=FALSE}
# get list of fire names
fire_names <- unique(fires_export$Fire_ID)
```

## Connect Landsat and High-Severity Patches

### Merge Rasters

```{r merge function, message=FALSE, warning=FALSE,results='hide'}
# function to merge rasters, if there are multiple in the folder
export_rasters <- function(fire_name){
  print(paste0("Starting Fire ",fire_name))
  
  # get list of this fire's tif files
  rast_list <- list.files(path = "data/landsat/landsat_annual", pattern=fire_name, all.files=TRUE, full.names=TRUE)
  
  # larger rasters were exported from GEE as multiple files, need to be combined before importing
  if (length(rast_list)>1) { 
    print(paste0(length(rast_list)," rasters, merging..."))
    rast_all <- lapply(rast_list, rast)
    rast_collection <- do.call(merge,rast_all)
    writeRaster(rast_collection, str_c("data/landsat/landsat_annual/",fire_name,".tif"), overwrite=FALSE,gdal="COMPRESS=NONE")
    } else { 
    print("Only one raster, can extract directly")
    }
}
```

```{r message=FALSE, warning=FALSE,eval=FALSE}
map(fire_names,export_rasters)
```

### Extract Landsat Data for Each Patch

```{r extract function, message=FALSE,warning=FALSE}
extract_landsat <- function(fire_name){
  print(paste0("Starting Fire ",fire_name))
  
  # get list of this fire's tif files
  rast_list <- list.files(path = "data/landsat/landsat_annual", pattern=str_c(fire_name,".tif"), all.files=TRUE, full.names=TRUE)
  rast_collection <- rast(rast_list)  

  # name the bands
  names(rast_collection) <- bandlist
  
  # verify crs
  crs(rast_collection) <- "EPSG: 4326"
  
  # filter the patches for this fire
  fire_patches <- patches %>% 
    filter(Fire_ID==fire_name) %>% 
    st_transform(crs=crs(rast_collection))
  
  # get the mean landsat values for each patch in this fire
  extracted_data <- left_join(fire_patches, exact_extract(rast_collection,fire_patches, append_cols = TRUE, max_cells_in_memory = 3e+08, fun = "mean")) %>% 
    st_drop_geometry()
  
  # export
  return(extracted_data)
}
```

```{r extract, message=FALSE, warning=FALSE, results='hide', cache=TRUE}
# map extraction function across all fires
extracted_fires <- map(fire_names,extract_landsat)

# combine dataset
landsat_dataset <- do.call(rbind, extracted_fires) %>% 
  st_drop_geometry()
```

## Prepare Dataset 

### Clean Data

```{r clean dataset}
# clean dataset, label, select only ndvi, calculate pre-fire ndvi & differenced ndvi
ndvi_dataset_full <- landsat_dataset %>% 
  mutate(Patch_ID = str_c(Fire_ID,"-",1:n()),
         prefire_yr = as.integer(year-1),
         patch_area_class = fct_relevel(as.factor(case_when(ptch_r_ >= 1000 ~ ">1000 acres",
                                                ptch_r_ < 1000 & ptch_r_ >= 500 ~ "500-1000 acres",
                                                ptch_r_ < 500 & ptch_r_ >= 100 ~ "100-500 acres",
                                                ptch_r_ < 100 & ptch_r_ >= 50 ~ "50-100 acres",
                                                ptch_r_ < 50 & ptch_r_ >= 10 ~ "10-50 acres",
                                                TRUE ~ "<10 acres")),">1000 acres",after = 5)) %>% 
  rename(fire_yr = year,
         patch_area = ptch_r_,
         patch_foresttype = ptch_fr,
         Event_ID = Evnt_ID,
         Incid_Name = Incd_Nm,
         ecoregion = ecoregn) %>% 
  dplyr::select(Event_ID, Incid_Name, Fire_ID, Patch_ID, prefire_yr, fire_yr, 
                ecoregion, patch_foresttype, patch_area, patch_area_class, contains("ndvi")) %>%
  pivot_longer(.,contains("ndvi"),names_to = "landsat_yr", values_to = "ndvi")%>% 
  mutate(landsat_yr = as.integer(landsat_yr %>%  stringr::str_remove("mean.ndvi")),
         years_postfire = landsat_yr - fire_yr) %>% 
  mutate(prefire_ndvi = case_when(years_postfire == -1 ~ ndvi)) %>% 
  group_by(Patch_ID) %>% 
  mutate(prefire_ndvi = mean(prefire_ndvi, na.rm=TRUE)) %>%
  ungroup() %>% 
  mutate(delta_ndvi = ndvi - prefire_ndvi)%>%  
  filter(patch_foresttype %in% c("Lodegepole Pine","Douglas-Fir","Fir-Spruce"))

# filter list to fires w/o reburning, planting, etc
ndvi_dataset <- ndvi_dataset_full %>% 
  filter(Fire_ID %in% c("Fire_31_1988","Fire_48_1990","Fire_18_1988","Fire_22_1988","Fire_16_1988","Fire_19_1988","Fire_20_1988","Fire_3_1988","Fire_50_1991","Fire_33_1989","Fire_26_1988","Fire_25_1988","Fire_14_1988","Fire_1_1988","Fire_11_1988","Fire_49_1991","Fire_29_1988","Fire_28_1988","Fire_7_1988","Fire_2_1988","Fire_12_1988","Fire_23_1988","Fire_38_1989","Fire_13_1988","Fire_46_1990","Fire_51_1991","Fire_32_1989","Fire_37_1989","Fire_15_1988","Fire_9_1988","Fire_4_1988","Fire_24_1988","Fire_10_1988","Fire_41_1989","Fire_54_1991","Fire_13_1988","Fire_42_1989"))
    
```

### Regroup Data

```{r group datasets, message=FALSE, warning=FALSE}
ndvi_grouped_type <- ndvi_dataset %>% 
  group_by(patch_foresttype,years_postfire) %>% 
  summarize(ndvi=mean(ndvi,na.rm=TRUE),
            delta_ndvi = mean(delta_ndvi,na.rm=TRUE)) %>% 
  drop_na()

ndvi_grouped_size <- ndvi_dataset %>% 
  group_by(patch_area_class,years_postfire) %>% 
  summarize(ndvi=mean(ndvi,na.rm=TRUE),
            delta_ndvi = mean(delta_ndvi,na.rm=TRUE)) %>% 
  drop_na() 

ndvi_grouped_ecoregion <- ndvi_dataset %>% 
  group_by(ecoregion,years_postfire) %>% 
  summarize(ndvi=mean(ndvi,na.rm=TRUE),
            delta_ndvi = mean(delta_ndvi,na.rm=TRUE)) %>% 
  drop_na() 

ndvi_grouped_eco_type<- ndvi_dataset %>% 
  group_by(ecoregion,patch_foresttype,years_postfire) %>% 
  summarize(ndvi=mean(ndvi,na.rm=TRUE),
            delta_ndvi = mean(delta_ndvi,na.rm=TRUE)) %>% 
  drop_na() 
```

## Plot

### Forest Type

```{r graphs!! type, message=FALSE, warning=FALSE}
# ggplot(ndvi_dataset ,aes(years_postfire,ndvi,color=patch_foresttype))+
#   geom_point(size=1) +
#   geom_smooth(method="auto",se=FALSE) +
#   labs(x="Year",y="NDVI",title= "All High-Severity Patch NDVI Change 30 Years Post-Fire", subtitle = "Comparing Forest Types", color = "Patch Forest Type")

# ggplot(ndvi_grouped_type,aes(years_postfire,delta_ndvi,color=patch_foresttype,group=patch_foresttype))+
#     geom_smooth(method="auto",se=FALSE) +
#   labs(x="Year",y="NDVI",title= "All High-Severity Patch NDVI Recovery 30 Years Post-Fire", subtitle = "Comparing Forest Types", color = "Patch Forest Type") +
#   geom_hline(yintercept= 0,linetype="dashed",color="black",size=1)
# 
# ggplot(ndvi_grouped_type ,aes(years_postfire,ndvi,color=patch_foresttype,group=patch_foresttype))+
#   geom_point(size=1) +
#   geom_smooth(method="auto",se=FALSE) +
#   labs(x="Year",y="NDVI",title= "NDVI Change Overtime 30 Years Post-Fire", subtitle = "Comparing Forest Types",color = "Forest Type")

ggplot(ndvi_grouped_type,aes(years_postfire,delta_ndvi,color=patch_foresttype,group=patch_foresttype))+
  geom_point(size=1) +
  geom_smooth(method="auto",se=FALSE) + 
  labs(x="Year",y="Change in NDVI from Pre-Fire",title= "NDVI Change Overtime 30 Years Post-Fire", subtitle = "Comparing Forest Types",color = "Forest Type") +
  geom_hline(yintercept= 0,linetype="dashed",color="black",size=1)
```

### Patch Area

```{r graphs!! size, message=FALSE, warning=FALSE}

# ggplot(ndvi_grouped_size,aes(years_postfire,ndvi,color=patch_area_class,group=patch_area_class))+
#   geom_point(size=1) +
#   geom_smooth(se=FALSE,method="auto") +
#   labs(x="Year",y="NDVI",title= "NDVI Change Overtime 30 Years Post-Fire", subtitle = "Comparing Patch Size",color = "Patch Size")

ggplot(ndvi_grouped_size,aes(years_postfire,delta_ndvi,color=patch_area_class,group=patch_area_class))+
  geom_point(size=1) +
  geom_smooth(se=FALSE,method="auto") +
  labs(x="Year",y="Change in NDVI from Pre-Fire",title= "NDVI Change Overtime 30 Years Post-Fire", subtitle = "Comparing Patch Size",color = "Patch Size") + 
  geom_hline(yintercept= 0,linetype="dashed",color="black",size=1)

```

### Ecoregion

```{r graphs!! eco, message=FALSE, warning=FALSE}
# ggplot(ndvi_grouped_ecoregion,aes(years_postfire,ndvi,color=ecoregion,group=ecoregion))+
#   geom_point(size=1) +
#   geom_smooth(se=FALSE,method="auto") +
#   labs(x="Year",y="NDVI",title= "NDVI Change Overtime 30 Years Post-Fire",subtitle= "Comparing Ecoegions",color = "Ecoregion") 

ggplot(ndvi_grouped_ecoregion,aes(years_postfire,delta_ndvi,color=ecoregion,group=ecoregion))+
  geom_point(size=1) +
  geom_smooth(se=FALSE,method="auto") +
  labs(x="Year",y="Change in NDVI from Pre-Fire",title= "NDVI Change Overtime 30 Years Post-Fire", subtitle= "Comparing Ecoegions",color = "Ecoregion") +
  geom_hline(yintercept= 0,linetype="dashed",color="black",size=1)
```

## Recovery

### Forest Type

```{r, message=FALSE, warning=FALSE}
ggplot(ndvi_grouped_type %>% filter(years_postfire>9),aes(years_postfire,delta_ndvi,color=patch_foresttype,group=patch_foresttype))+
  geom_point(size=1) +
  geom_smooth(method="lm",se=FALSE) + 
  labs(x="Year",y="Change in NDVI from Pre-Fire",title= "NDVI Change Overtime 10-30 Years Post-Fire", subtitle = "Comparing Forest Types",color = "Forest Type") +
  geom_hline(yintercept= 0,linetype="dashed",color="black",size=1)
```

```{r}
# model NDVI difference for each forest type
model_ndvi <- ndvi_grouped_type%>% 
  filter(years_postfire>9) %>% 
  split(f = .$patch_foresttype) %>% 
  map(function(df) 
  lm(delta_ndvi ~ years_postfire, data = df))

model_ndvi_df <- as.data.frame(do.call(rbind,map(model_ndvi, coef))) %>% 
  rownames_to_column("patch_foresttype") %>% 
  rename(intercept = "(Intercept)",
         slope = years_postfire) %>% 
  mutate(years_recovery = -intercept / slope)

kable(model_ndvi_df, 
      align = 'c',
      padding = 1,
      col.names = c("Forest Type", "Intercept", "Slope", "Est Years to Pre-Fire NDVI"),
      caption = "Estimated NDVI Recovery by Forest Type")

tab_model(model_ndvi,dv.labels=c("Douglas-Fir","Fir-Spruce","Lodgepole Pine"),digits=3)

```

### Ecoregion

```{r, message=FALSE, warning=FALSE}
ggplot(ndvi_grouped_ecoregion %>% filter(years_postfire>9),aes(years_postfire,delta_ndvi,color=ecoregion,group=ecoregion))+
  geom_point(size=1) +
  geom_smooth(method="lm",se=FALSE) + 
  labs(x="Year",y="Change in NDVI from Pre-Fire",title= "NDVI Change Overtime 10-30 Years Post-Fire", subtitle = "Comparing Ecoregions",color = "Ecoregion") +
  geom_hline(yintercept= 0,linetype="dashed",color="black",size=1)
```

```{r}
# model NDVI difference for each forest type
model_eco <- ndvi_grouped_ecoregion%>% 
  filter(years_postfire>9) %>% 
  split(f = .$ecoregion) %>% 
  map(function(df) 
  lm(delta_ndvi ~ years_postfire, data = df))

model_eco_df <- as.data.frame(do.call(rbind,map(model_eco, coef)))%>% 
  rownames_to_column(var = "ecoregion") %>% 
  rename(intercept = "(Intercept)",
         slope = years_postfire) %>% 
  mutate(years_recovery = -intercept / slope)

kable(model_eco_df, 
      align = 'c',
      padding = 1,
      col.names = c("Ecoregion", "Intercept", "Slope", "Est Years to Pre-Fire NDVI"),
      caption = "Estimated NDVI Recovery by Ecoregion")

tab_model(model_eco,dv.labels=unique(model_eco_df$ecoregion),digits=3)

```

### Ecoregion and Forest Type

```{r, message=FALSE, warning=FALSE}
ggplot(ndvi_grouped_eco_type %>% filter(years_postfire>9),aes(years_postfire,delta_ndvi,color=ecoregion))+
  geom_point(size=1) + 
  geom_smooth(method="lm",se=FALSE) +
  labs(x="Year",y="Change in NDVI from Pre-Fire",title= "NDVI Change Overtime 10-30 Years Post-Fire", subtitle = "Comparing Forest Types Across Ecoregions",color = "Forest Type", linetype = "Ecoregion") +
  geom_hline(yintercept= 0,linetype="dashed",color="black",size=1) +
  facet_wrap(~ patch_foresttype)

ggplot(ndvi_grouped_eco_type %>% filter(years_postfire>9),aes(years_postfire,delta_ndvi,color=patch_foresttype))+
  geom_point(size=1) + 
  geom_smooth(method="lm",se=FALSE) +
  labs(x="Year",y="Change in NDVI from Pre-Fire",title= "NDVI Change Overtime 10-30 Years Post-Fire", subtitle = "Comparing Forest Types Across Ecoregions",color = "Forest Type", linetype = "Ecoregion") +
  geom_hline(yintercept= 0,linetype="dashed",color="black",size=1) +
  facet_wrap(~ ecoregion)
```

```{r}
# model NDVI difference for each forest type
model_eco_type <- ndvi_grouped_eco_type%>% 
  filter(years_postfire>9) %>% 
  split(f = list(.$ecoregion,.$patch_foresttype)) %>% 
  map(function(df) 
  lm(delta_ndvi ~ years_postfire, data = df))

model_eco_type_df <- as.data.frame(do.call(rbind,map(model_eco_type, coef)))%>% 
  rownames_to_column(var = "ecoregion_foresttype") %>% 
  rename(intercept = "(Intercept)",
         slope = years_postfire) %>% 
  mutate(years_recovery = -intercept / slope) %>% 
  within(., do.call('rbind', strsplit(as.character(ecoregion_foresttype), '.', fixed=TRUE)))


kable(model_eco_type_df, 
      align = 'c',
      padding = 1,
      col.names = c("Ecoregion + ForestType", "Intercept", "Slope", "Est Years to Pre-Fire NDVI"),
      caption = "Estimated NDVI Recovery by Ecoregion")

tab_model(model_eco_type[1:4],dv.labels=unique(model_eco_df$ecoregion),digits=3,title="Douglas-Fir")
tab_model(model_eco_type[5:8],dv.labels=unique(model_eco_df$ecoregion),digits=3,title="Fir-Spruce")
tab_model(model_eco_type[9:12],dv.labels=unique(model_eco_df$ecoregion),digits=3,title="Lodgepole Pine")
```

```{r}
# including patch as random effect

# model_ndvi_full <- ndvi_dataset%>% 
#   filter(years_postfire>9) %>% 
#   drop_na() %>%
#   split(f = .$patch_foresttype) %>% 
#   map(function(df) 
#   lme4::lmer(delta_ndvi ~ years_postfire + (1|Patch_ID), data = df))
# 
# model_ndvi_full_df <- as.data.frame(do.call(rbind,map(model_ndvi_full, coef)))%>% 
#   rownames_to_column(var = "ecoregion_foresttype")
# 
# %>% 
#   rename(intercept = "(Intercept)",
#          slope = years_postfire) %>% 
#   mutate(years_recovery = -intercept / slope) %>% 
#   within(., do.call('rbind', strsplit(as.character(ecoregion_foresttype), '.', fixed=TRUE)))

```


