# Prediction

## Set Up

### Libraries

```{r libraries7, message=FALSE, warning=FALSE}
library(sf)
library(terra)
library(tidyverse)
library(ggplot2)
library(randomForest)
library(raster)
library(mapview)
```

### Import Fire Boundaries

```{r patches and fire import, message=FALSE, warning=FALSE, results='hide'}
# import high-severity patches
patches <- st_read("data/patches/highsev_patches.shp") %>% 
  st_transform(crs="EPSG: 4326")

# set crs
crs <- crs(patches)

# import fire boundaries
fires_export <- st_read("data/fire_boundaries/fires_export.shp")%>% 
  st_transform(., crs=crs)
```

### Import Models

```{r}
rf_conifer <- readRDS("data/models/rf_conifer.rds")
lm_conifer <- readRDS("data/models/lm_conifer.rds")
```


### Prepare Raster Naming

#### Bands
```{r band names2, message=FALSE, warning=FALSE}
# list band names and years
bands <- c("blue", "green", "red", "nir", "swir1", "swir2", "ndvi", "ndwi", "nbr", "nbr2", "ndsi", "ndfsi", "evi")
years <- c(1984:2020)

# create list of all combinations of bands, in the appropriate order
bandnames <- list(bands,years) %>%
  cross() %>%
  map(lift(paste0))

bandlist <- do.call(rbind,bandnames)
```

#### Fire Names

```{r fire names2, message=FALSE, warning=FALSE}
# get list of fire names
fire_names <- unique(fires_export$Fire_ID)
```


## Prediction Rasters

### Predict Across Rasters

```{r prediction function, message=FALSE,warning=FALSE}

predict_landsat_lm <- function(fire_name){
  print(paste0("Starting Fire ",fire_name))
  
  # import fire raster
  rast_list <- list.files(path = "data/landsat/landsat_annual", pattern=str_c(fire_name,".tif"), all.files=TRUE, full.names=TRUE)
  fire_raster <- rast(rast_list)  

  # name the bands, verify crs
  names(fire_raster) <- bandlist
  crs(fire_raster) <- "EPSG: 4326"
  
    # filter the patches for this fire
  fire_patches <- patches %>% 
    filter(Fire_ID==fire_name) %>% 
    st_transform(crs=crs(fire_raster))
  
  # clip raster to patches
  raster_clip <- mask(fire_raster,fire_patches)
  
  # set fire year
  fire_year_start <- mean(fire_patches$year)
  fire_year_end <- fire_year_start + 30
  
  # string of start years for 3-year image composites
  fire_year_seq <- sequence(10,from=fire_year_start, by = 3)
  
  pred_rasters <- list()
  for(i in 1:10){
    print(i)
    
    raster_yr1 <- raster_clip[as.character(fire_year_seq[i])]
    raster_yr2 <- raster_clip[as.character(fire_year_seq[i]+1)]
    raster_yr3 <- raster_clip[as.character(fire_year_seq[i]+2)]
    
    names(raster_yr1) <- list("blue", "green", "red", "nir", "swir1", "swir2", "ndvi", "ndwi", "nbr", "nbr2", "ndsi", "ndfsi", "evi")
    names(raster_yr2) <- list("blue", "green", "red", "nir", "swir1", "swir2", "ndvi", "ndwi", "nbr", "nbr2", "ndsi", "ndfsi", "evi")
    names(raster_yr3) <- list("blue", "green", "red", "nir", "swir1", "swir2", "ndvi", "ndwi", "nbr", "nbr2", "ndsi", "ndfsi", "evi")
    
    raster_set <- mean(raster_yr1,raster_yr2,raster_yr3,na.rm=TRUE)
    
    rast_predicted <- terra::predict(raster_set,lm_conifer, type="response", se.fit=TRUE)
    
    pred_rasters[str_c("year",1+((i-1)*3),"to",i*3)] <- rast_predicted
  }
  
  # export
  return(pred_rasters)
}

predict_landsat_rf <- function(fire_name){
  print(paste0("Starting Fire ",fire_name))
  
  # import fire raster
  rast_list <- list.files(path = "data/landsat/landsat_annual", pattern=str_c(fire_name,".tif"), all.files=TRUE, full.names=TRUE)
  fire_raster <- rast(rast_list)  

  # name the bands, verify crs
  names(fire_raster) <- bandlist
  crs(fire_raster) <- "EPSG: 4326"
  
    # filter the patches for this fire
  fire_patches <- patches %>% 
    filter(Fire_ID==fire_name) %>% 
    st_transform(crs=crs(fire_raster))
  
  # clip raster to patches
  raster_clip <- mask(fire_raster,fire_patches)
  
  # set fire year
  fire_year_start <- mean(fire_patches$year)
  fire_year_end <- fire_year_start + 30
  
  # string of start years for 3-year image composites
  fire_year_seq <- sequence(10,from=fire_year_start, by = 3)
  
  pred_rasters <- list()
  for(i in 1:10){
    print(i)
    
    raster_yr1 <- raster_clip[as.character(fire_year_seq[i])]
    raster_yr2 <- raster_clip[as.character(fire_year_seq[i]+1)]
    raster_yr3 <- raster_clip[as.character(fire_year_seq[i]+2)]
    
    names(raster_yr1) <- list("blue", "green", "red", "nir", "swir1", "swir2", "ndvi", "ndwi", "nbr", "nbr2", "ndsi", "ndfsi", "evi")
    names(raster_yr2) <- list("blue", "green", "red", "nir", "swir1", "swir2", "ndvi", "ndwi", "nbr", "nbr2", "ndsi", "ndfsi", "evi")
    names(raster_yr3) <- list("blue", "green", "red", "nir", "swir1", "swir2", "ndvi", "ndwi", "nbr", "nbr2", "ndsi", "ndfsi", "evi")
    
    raster_set <- mean(raster_yr1,raster_yr2,raster_yr3,na.rm=TRUE)
    
    rast_predicted <- terra::predict(raster_set,rf_conifer, type="response", se.fit=TRUE)
  
    
    pred_rasters[str_c("year",1+((i-1)*3),"to",i*3)] <- rast_predicted
  }
  
  # export
  return(pred_rasters)
}
```


```{r message=FALSE, warning=FALSE, cache = TRUE, results='hide', eval= FALSE}

# create dataset of prediction rasters for each model in 3 year increments
prediction_dataset_lm <- map(fire_names,predict_landsat_lm)

names(prediction_dataset_lm) <- fire_names

prediction_dataset_rf <- map(fire_names,predict_landsat_rf)

names(prediction_dataset_rf) <- fire_names


# rast_predicted[rast_predicted < .5] <- 0
# rast_predicted[rast_predicted >= .5] <- 1
```


```{r}
# test <- prediction_dataset_lm$Fire_21_1988$year1to3
# test2 <- prediction_dataset_lm$Fire_21_1988$year16to18
# test3 <- prediction_dataset_lm$Fire_21_1988$year28to30
# 
# 
# mapview(raster(test)) + mapview(raster(test2)) + mapview(raster(test3))
```

