# Landscape Metrics

## Set Up

### Import Libraries
```{r libraries 9, message=FALSE, warning=FALSE}
library(sf)
library(terra)
library(mapview)
library(raster)
library(tidyverse)
library(ggplot2) 
library(landscapemetrics)
```

### Import Patch Polygons

```{r import patch3, message=FALSE, warning=FALSE}
# fire list
fire_list <- c("Fire_1_1988","Fire_2_1988","Fire_3_1988","Fire_4_1988","Fire_7_1988","Fire_9_1988","Fire_10_1988","Fire_11_1988","Fire_12_1988","Fire_13_1988","Fire_14_1988","Fire_15_1988","Fire_16_1988","Fire_18_1988","Fire_19_1988","Fire_20_1988","Fire_22_1988","Fire_23_1988","Fire_25_1988","Fire_26_1988","Fire_28_1988","Fire_29_1988","Fire_31_1988","Fire_32_1989","Fire_33_1989","Fire_35_1989","Fire_38_1989","Fire_41_1989","Fire_42_1989","Fire_48_1990","Fire_49_1991","Fire_50_1991","Fire_51_1991","Fire_54_1991")

# import high-severity patches
patches <- st_read("data/patches/highsev_patches.shp") %>% 
  mutate(Patch_ID = str_c(Fire_ID,"-",1:n())) %>% 
  st_transform(crs = "EPSG:4326")

# set crs
crs <- crs(patches)

# import fire boundaries
fires_export <- st_read("data/fire_boundaries/fires_export.shp") %>% 
  st_tranform(crs = crs)
```

```{r}
get_lsm <- function(fire_name){
  print(fire_name)
  rast_list <- list.files(path = "data/prediction_rasters", pattern = str_c(fire_name,"_rf"), all.files=TRUE, full.names=TRUE)
  rast_names <- str_sub(rast_list,start = -6, end = -5)  
  rast_fire <- rast(rast_list)
  names(rast_fire) <- rast_names

  fire_df <- list()

  for(i in rast_names){
    print(i)
    
    # set up rasters
    rast_fire_tp <- rast_fire[[i]] %>% 
        as.factor() %>% 
        terra::project(.,"EPSG: 3857")

    patches_fire <- patches %>% 
      filter(Fire_ID == fire_name) %>% 
      st_transform(crs = "EPSG: 3857")
    
    lsm_df <- list()
    
    for(j in unique(patches_fire$Patch_ID)){
      print(j)

      patch_patch <- patches_fire %>% 
        filter(Patch_ID == j)
      
      masked_rast <- mask(rast_fire_tp,patch_patch) 
      
      if(all(is.na(values(masked_rast))) == FALSE){
  
        patch_lsm <- calculate_lsm(masked_rast, 
                                   what = c("lsm_c_clumpy","lsm_c_ai","lsm_c_enn_mn","lsm_c_cohesion",
                                             "lsm_c_pland","lsm_c_np","lsm_c_ca",
                                             "lsm_c_area_mn","lsm_l_contag"), 
                                   count_boundary=TRUE) %>% 
          mutate(value = round(value,digits = 4),
                 timepoint = i,
                 Fire_ID = fire_name,
                 patch_foresttype = patch_patch$ptch_fr,
                 ecoregion = patch_patch$ecoregn, 
                 patch_area = patch_patch$ptch_r_,
                 Patch_ID = j) %>% 
          pivot_wider(.,names_from = metric,values_from = value) %>% 
          group_by(timepoint) %>% 
          mutate(contag=mean(contag,na.rm=TRUE))%>% 
          ungroup() %>% 
          filter(class == 2)
  
          lsm_df[[j]] <- patch_lsm
      } else{
        lsm_df[[j]] <- data.frame(row.names = c("empty"))
      }
    } 
    lsm_df_fire <- do.call(rbind,lsm_df)
    fire_df[[i]] <- lsm_df_fire
  }
  return(fire_df)
}
```


```{r message=FALSE, warning=FALSE}
subset <- fire_list[8:34]

lsm_df_allfires <- map(subset,get_lsm)  
lsm_dataset <- as_tibble(do.call(rbind, do.call(rbind,lsm_df_allfires)))%>% 
  filter(timepoint != "t0")

colnames(lsm_dataset)
```


```{r}
lsm_dataset_type <- lsm_dataset %>% 
  filter(timepoint != "t0",
         patch_foresttype == c("Douglas-Fir","Fir-Spruce","Lodegepole Pine")) %>% 
  group_by(patch_foresttype,timepoint) %>% 
  summarize(pland = mean(pland,na.rm=TRUE),
            contag = mean(contag,na.rm=TRUE),
            ai = mean(ai,na.rm=TRUE),
            clumpy = mean(clumpy,na.rm=TRUE),
            enn_mn = mean(enn_mn,na.rm=TRUE),
            cohesion= mean(cohesion,na.rm=TRUE))
```


```{r}
# ggplot(lsm_dataset_type,aes(timepoint,cohesion,group = patch_foresttype,color=patch_foresttype)) + 
#   geom_point(size = 1) +
#   geom_smooth(se=FALSE) + 
#   labs(title = "Presence Cohension",subtitle="asses if patches of the same class are located aggregated or rather isolated")

ggplot(lsm_dataset_type,aes(timepoint,pland,group = patch_foresttype,color=patch_foresttype)) + 
  geom_point(size = 1) +
  geom_smooth(se=FALSE) + 
  labs(title = "Percent of Patch Area Forested")

ggplot(lsm_dataset_type ,aes(timepoint,enn_mn,group = patch_foresttype,color=patch_foresttype)) + 
  geom_point(size = 1) +
  geom_smooth(se=FALSE) + 
  labs(title = "Nearest Neighbor Distances (m)")

ggplot(lsm_dataset_type,aes(timepoint,contag,group = patch_foresttype,color=patch_foresttype)) + 
  geom_point(size = 1) +
  geom_smooth(se=FALSE) + 
  labs(title = "Landscape Contagion",subtitle = " 0 if all cells are unevenly distributed and 100 indicates that all cells are equally adjacent to all other classes")

ggplot(lsm_dataset_type,aes(timepoint,ai,group = patch_foresttype,color=patch_foresttype)) + 
  geom_point(size = 1) +
  geom_smooth(se=FALSE) + 
  labs(title = "Aggregation Index",subtitle = "number of like adjacencies divided by the theoretical maximum possible number of like adjacencies")


```

