# Edge Encroachment

## Set Up

### Import Libraries

```{r libraries 10, message=FALSE, warning=FALSE}
library(sf)
library(terra)
library(mapview)
library(raster)
library(tidyverse)
library(ggplot2) 
library(exactextractr)
```

### Import Patch Polygons

```{r import patch4, message=FALSE, warning=FALSE}
# fire list
fire_list <- c("Fire_1_1988","Fire_2_1988","Fire_3_1988","Fire_4_1988","Fire_7_1988","Fire_9_1988","Fire_10_1988","Fire_11_1988","Fire_12_1988","Fire_13_1988","Fire_14_1988","Fire_15_1988","Fire_16_1988","Fire_18_1988","Fire_19_1988","Fire_20_1988","Fire_22_1988","Fire_23_1988","Fire_25_1988","Fire_26_1988","Fire_28_1988","Fire_29_1988","Fire_31_1988","Fire_32_1989","Fire_33_1989","Fire_35_1989","Fire_38_1989","Fire_41_1989","Fire_42_1989","Fire_48_1990","Fire_49_1991","Fire_50_1991","Fire_51_1991","Fire_54_1991")

# import high-severity patches
patches <- st_read("data/patches/highsev_patches.shp") %>% 
  mutate(Patch_ID = str_c(Fire_ID,"-",1:n())) %>% 
  st_transform(crs = "EPSG:4326")

patch_list <- unique(patches$Patch_ID)

# set crs 
crs <- crs(patches)

# import fire polygons
fires_export <- st_read("data/fire_boundaries/fires_export.shp") %>% 
  st_transform(crs = crs)
```

## Calculate Landscape Patterns

```{r message=FALSE, warning=FALSE}
# function to create distance dataset for each fire's time steps
get_timesteps <- function(rast_name,patch_name,patch,rast_patch){
  print(rast_name)
  
  # select the timepoint and corresponding raster
  timepoint2 <- rast_name
  timepoint2_raster <- rast_patch[[timepoint2]]  %>% 
    as.factor()  %>% 
    terra::project(.,"EPSG: 3857")
  
  timepoint1 <- str_c("t",as.numeric(str_sub(timepoint2,2,2))-1)
  timepoint1_raster <- rast_patch[[timepoint1]]  %>% 
    as.factor() %>% 
    terra::project(.,"EPSG: 3857")
  
  timepoint_difference_raster <- timepoint2_raster - timepoint1_raster 

  values(timepoint2_raster)[is.na(values(timepoint2_raster))] <- 3
  distance_rast <- distance(timepoint2_raster, target = 2, exclude = 1, unit = "m")
  distance_rast[distance_rast == 0 ] <- NA
  allgrowth_distance_df <- as.data.frame(distance_rast) %>% 
    mutate(Patch_ID = patch_name,
           Fire_ID = patch$Fire_ID,
           forest_type = patch$ptch_fr,
           ecoregion = patch$ecoregn,
           timepoint = rast_name,
           growth_type = "all growth") %>% 
    rename("edge_dist_m" = "label")
  
  # of new growth
  values(timepoint_difference_raster)[is.na(values(timepoint_difference_raster))] <- 3
  timepoint_difference_raster[timepoint_difference_raster == -1 ] <- 0
  distance_rast_new <- distance(timepoint_difference_raster, target = 1, exclude = 0, unit = "m")
  distance_rast_new[distance_rast_new == 0 ] <- NA
  newgrowth_distance_df <- as.data.frame(distance_rast_new) %>% 
    mutate(Patch_ID = patch_name,
           Fire_ID = patch$Fire_ID,
           forest_type = patch$ptch_fr,
           ecoregion = patch$ecoregn,
           timepoint = rast_name,
           growth_type = "only new") %>% 
    rename("edge_dist_m" = "label")
  
  growth_df <- rbind(allgrowth_distance_df,newgrowth_distance_df)
  
  return(growth_df)
}
```

```{r message=TRUE, warning=FALSE}
get_distances <- function(patch_name,patches){
  # print patch ID 
  print(patch_name)
  
  # filter to this specific patch
  patch <- patches %>% 
    filter(Patch_ID == patch_name)
  
  # get fire ID
  fire_name <- patch$Fire_ID

  # import and name rasters for that fire
  rast_list <- list.files(path = "data/prediction_rasters", pattern = str_c(fire_name,"_rf"), all.files=TRUE, full.names=TRUE)
  rast_names <- str_sub(rast_list,start = -6, end = -5)  
  rast_fire <- rast(rast_list)
  names(rast_fire) <- rast_names
    
  loop_names <- rast_names[2:10]
  
  # mask raster to the specific patch
  rast_patch <- mask(rast_fire,patch)

  dist_fullset <- lapply(loop_names,
                      get_timesteps,
                      patch_name=patch_name,patch=patch,rast_patch=rast_patch)
    
  dist_df <- do.call(rbind,dist_fullset)
  
  return(dist_df)
}
```


```{r}
for(i in patch_list){
  dist <- get_distances(i,patches)
  st_write(dist, str_c("data/distances/",i,".csv"))
}

ggplot(test %>% filter(growth_type == "only new"),aes(edge_dist_m)) +
  geom_histogram() +
  facet_wrap(~timepoint)
ggplot(test %>% filter(growth_type == "all growth"),aes(edge_dist_m)) +
  geom_histogram() +
  facet_wrap(~timepoint)
```

