
# Patch Metrics

## Set Up

### Libraries
```{r libraries11, message=FALSE, warning=FALSE}
library(tidyverse)
library(terra)
library(sf)
library(ggsankey)
library(gridExtra)

sf_use_s2(FALSE)
```

### Import High-Severity Patches

```{r import patch4, message=FALSE, warning=FALSE}
# fire list
fire_list <- c("Fire_7_1988","Fire_9_1988","Fire_10_1988","Fire_11_1988","Fire_12_1988","Fire_13_1988","Fire_14_1988","Fire_15_1988","Fire_16_1988","Fire_18_1988","Fire_19_1988","Fire_20_1988","Fire_22_1988","Fire_23_1988","Fire_25_1988","Fire_26_1988","Fire_28_1988","Fire_29_1988","Fire_31_1988","Fire_32_1989","Fire_33_1989","Fire_35_1989","Fire_38_1989","Fire_41_1989","Fire_42_1989","Fire_48_1990","Fire_49_1991","Fire_50_1991","Fire_51_1991","Fire_54_1991","Fire_1_1988","Fire_2_1988","Fire_3_1988","Fire_4_1988")

# import high-severity patches
patches <- st_read("data/patches/highsev_patches.shp") %>% 
  mutate(Patch_ID = str_c(Fire_ID,"-",1:n())) %>% 
  st_transform(crs = "EPSG:4326")

# set crs
crs <- crs(patches)
```
### Create Dataset for Each Forest Type

```{r message=FALSE, warning=FALSE}
# import and join all decomposiition csvs
patch_data <- do.call(bind_rows,lapply(list.files(path = "data/patch_fate", pattern = "Fire", all.files=TRUE, full.names=TRUE),read_csv))%>% 
  mutate(t0_group = case_when(t0_area > 1000 ~ "1000ha+",
                                t0_area > 500 & t0_area <1000 ~ "500-1000ha",
                                t0_area > 100 & t0_area <5000 ~ "100-500ha",
                                t0_area > 50 & t0_area <100~ "50-100ha",
                                t0_area < 50 ~ "0-50ha"),
           t9_group = case_when(lyr1 == 1 & t9_area > 1000 ~ "1000ha+",
                                lyr1 == 1 & t9_area > 500 & t9_area <1000 ~ "500-1000ha",
                                lyr1 == 1 & t9_area > 100 & t9_area <5000 ~ "100-500ha",
                                lyr1 == 1 & t9_area > 50 & t9_area <100~ "50-100ha",
                                lyr1 == 1 & t9_area < 50 ~ "0-50ha",
                                lyr1 == 2 ~ "forested"))
```
## Plot

## Identify Patches with Remaining Unforested Areas

```{r}
patch_list <- patch_data %>% 
  group_by(Patch_ID,lyr1) %>% 
  summarize(t0_area = mean(t0_area),
            t9_area = round(sum(t9_area),5)) %>% 
  pivot_wider(values_from = t9_area,names_from=lyr1) %>% 
  rename(t9_area_unforested = 4,
         t9_area_forested = 3) %>% 
  replace(is.na(.), 0) %>% 
  mutate(perc_forested = t9_area_forested/(t9_area_forested+t9_area_unforested),
         recovered = case_when(perc_forested <= .9 ~ "no",
                               TRUE ~ "yes"))

# write_csv(patch_list,"data/patches/patch_recovery_status.csv") 
```

```{r}
patch_metrics <- patches %>% 
  dplyr::select(Fire_ID,Patch_ID,ptch_fr,ecoregn) %>% 
  st_transform(3488) %>% 
  mutate(patch_area = round(as.numeric(st_area(.))/10000,4),
         perim_m = as.numeric(round(st_length(st_cast(geometry,to = "MULTILINESTRING")),4)),
         edge_perim_rat = patch_area/perim_m) %>% 
  st_buffer(-100) %>% 
  mutate(core_area = round(as.numeric(st_area(.))/10000,4),
         perc_core = round(core_area / patch_area,5))%>% 
  st_drop_geometry()
```


```{r}
patch_recovery <- left_join(patch_list,patch_metrics,by = "Patch_ID") %>% 
  # mutate(t0_group = case_when(t0_area > 1000 ~ "1000ha+",
  #                               t0_area > 500 & t0_area <1000 ~ "500-1000ha",
  #                               t0_area > 100 & t0_area <5000 ~ "100-500ha",
  #                               t0_area > 50 & t0_area <100~ "50-100ha",
  #                               t0_area < 50 ~ "0-50ha"))
  drop_na()%>% 
  filter(ptch_fr %in% c("Douglas-Fir","Lodegepole Pine","Fir-Spruce")) %>% 
  mutate(core_type = case_when (perc_core > 0.25 ~ "high",
                                TRUE ~ "low"))
# core area on regeneration
core_df <- patch_recovery %>% 
  group_by (ptch_fr,core_type,recovered) %>% 
  summarize (n = n()) %>% 
  mutate(perc_recovered = n/sum(n)*100) %>% 
  filter(recovered == "yes")
ggplot(core_df,aes(ptch_fr,perc_recovered,fill = core_type))+
  geom_col(position = "dodge")

# model checks
# core area on regeneration
lm_recovery <- lm(perc_forested ~ perc_core + edge_perim_rat  + ptch_fr + ecoregn, data = patch_recovery)
summary(lm_recovery)

lm_recovery <- lm(perc_forested ~ perc_core, data = patch_recovery)
summary(lm_recovery)
cor(patch_recovery$perc_forested,patch_recovery$perc_core)
  
# histogram of core area % for all patches
ggplot(patch_recovery %>% filter(perc_core > 0),aes(perc_core)) +
  geom_histogram() + 
  facet_wrap(~ptch_fr)

# histogram of patch recovery % for all patches
ggplot(patch_recovery ,aes(perc_forested)) +
  geom_histogram() + 
  facet_wrap(~ptch_fr)

```

