# Landscape Expansion

## Set Up

### Import Libraries

```{r libraries 10, message=FALSE, warning=FALSE}
library(sf)
library(terra)
library(mapview)
library(raster)
library(tidyverse)
library(ggplot2) 
library(exactextractr)
```

### Import Patch Polygons

```{r import patch4, message=FALSE, warning=FALSE}
# fire list
fire_list <- c("Fire_54_1991","Fire_4_1988","Fire_7_1988","Fire_9_1988","Fire_10_1988","Fire_11_1988","Fire_12_1988","Fire_13_1988","Fire_14_1988","Fire_15_1988","Fire_16_1988","Fire_18_1988","Fire_19_1988","Fire_20_1988","Fire_22_1988","Fire_23_1988","Fire_25_1988","Fire_26_1988","Fire_28_1988","Fire_29_1988","Fire_31_1988","Fire_32_1989","Fire_33_1989","Fire_35_1989","Fire_38_1989","Fire_41_1989","Fire_42_1989","Fire_48_1990","Fire_49_1991","Fire_50_1991","Fire_51_1991","Fire_1_1988","Fire_2_1988","Fire_3_1988")

# import high-severity patches
patches <- st_read("N:/Public/WeekLong/Menick/highsev_patches.shp") %>% 
  mutate(Patch_ID = str_c(Fire_ID,"-",1:n())) %>% 
  st_transform(crs = "EPSG:4326")

# set crs 
crs <- crs(patches)

# import fire polygons
fires_export <- st_read("data/fire_boundaries/fires_export.shp") %>% 
  st_transform(crs = crs)
```

## Calculate Landscape Patterns

```{r message=TRUE, warning=FALSE}
fire_name <- "Fire_3_1988"

get_lei <- function(fire_name,fires_export){
  # print patch ID 
  print(fire_name)
  
  # filter to this specific patch
  patches_fire <- patches %>% 
    filter(Fire_ID == fire_name)

  # import and name rasters for that fire
  rast_list <- list.files(path = "data/prediction_rasters", pattern = str_c(fire_name,"_rf"), all.files=TRUE, full.names=TRUE)
  rast_names <- str_sub(rast_list,start = -6, end = -5)  
  rast_fire <- rast(rast_list)
  names(rast_fire) <- rast_names
    
  loop_names <- rast_names[2:10]
  
  lei_fullset <- lapply(loop_names,
                        get_timesteps,
                        rast_fire=rast_fire,patches_fire=patches_fire)
  
  lei_df <- do.call(rbind,lei_fullset)
  
  return(lei_df)
}
```

```{r message=FALSE, warning=FALSE}
rast_name <- "t1"

# function to create LEI dataset for each fire's time steps
get_timesteps <- function(rast_name,rast_fire,patches_fire){
  print(rast_name)
  
  # select the timepoint and corresponding raster
  timepoint2 <- rast_name
  timepoint2_raster <- rast_fire[[timepoint2]]  %>% 
      as.factor() 
  
  ### LEI ###
  # set up raster for the previous timepoint
  timepoint1 <- str_c("t",as.numeric(str_sub(timepoint2,2,2))-1)
  timepoint1_raster <- rast_fire[[timepoint1]]  %>% 
    as.factor() 

  # set area outside of patches to presence
  timepoint1_raster[is.na(timepoint1_raster)] <- 2
  
  # difference the two time points to identify areas of change
  timepoint_difference_raster <- timepoint2_raster - timepoint1_raster 

  # convert areas of new presence to polgyons
  timepoint_difference_polys <- as.polygons(timepoint_difference_raster) %>%
    st_as_sf() %>%
    st_cast("POLYGON") %>% 
    filter(.[[1]] == 1) %>% 
    st_transform(crs=crs) %>% 
    st_join(.,patches_fire)

  lei_df<- data.frame()
  for(i in str_sort(unique(timepoint_difference_polys$Patch_ID))){
    print(i)
    patch <- patches_fire %>% 
      filter(Patch_ID ==i)
    newgrowth_patch <- timepoint_difference_polys %>% 
      filter(Patch_ID == i) %>% 
      summarize(geometry= st_union(geometry))
    newgrowth_buffer <- st_as_sf(buffer(vect(newgrowth_patch),100)) %>%
      summarize(geometry = st_union(geometry))
    newgrowth_ring <- st_difference(newgrowth_buffer,newgrowth_patch)
    raster_ring <- mask(timepoint1_raster,newgrowth_ring)
    freq_df <- freq(raster_ring) %>% 
      mutate(lei = count/sum(count),
             Patch_ID = i)%>% 
      filter(value ==2) %>% 
      select(-layer,-value)%>% 
      mutate(lei_category = case_when(lei > 0.5 ~ "infill",
                                      lei < .01 ~ "leapfrog",
                                      TRUE ~ "expansion"),
             timepoint = rast_name)
    
    lei_df <- rbind(lei_df,freq_df)
  }

  write_csv(lei_df,str_c("data/lei_simple/",fire_name,"-",rast_name,".csv"))
} 
```

```{r message=FALSE, warning=FALSE}


done<- c("Fire_10_1988","Fire_11_1988","Fire_12_1988","Fire_13_1988","Fire_14_1988","Fire_15_1988","Fire_16_1988","Fire_9_1988","Fire_54_1991","Fire_4_1988")
fire_list <- c("Fire_18_1988","Fire_19_1988","Fire_20_1988","Fire_22_1988","Fire_23_1988","Fire_25_1988","Fire_26_1988","Fire_28_1988","Fire_7_1988","Fire_29_1988","Fire_31_1988","Fire_32_1989","Fire_33_1989","Fire_35_1989","Fire_38_1989","Fire_41_1989","Fire_42_1989","Fire_48_1990","Fire_49_1991","Fire_50_1991","Fire_51_1991","Fire_1_1988","Fire_2_1988","Fire_3_1988")

# could potentially do the st_join with each patch instead of all patches; issue is then i go through all patches instead of those with growth

for(i in fire_list){
  lei_fulldataset <- get_lei(i,fires_export)
  write_csv(lei_fulldataset,str_c("data/lei_simple/",i,".csv"))
}
```















