# Landscape Expansion

## Set Up

### Import Libraries

```{r libraries9, message=FALSE, warning=FALSE}
library(sf)
library(terra)
library(mapview)
library(raster)
library(tidyverse)
library(ggplot2) 
library(exactextractr)
```

### Import Patch Polygons

```{r import patch5, message=FALSE, warning=FALSE}
# fire list
fire_list <- c("Fire_54_1991","Fire_4_1988","Fire_7_1988","Fire_9_1988","Fire_10_1988","Fire_11_1988","Fire_12_1988","Fire_13_1988","Fire_14_1988","Fire_15_1988","Fire_16_1988","Fire_18_1988","Fire_19_1988","Fire_20_1988","Fire_22_1988","Fire_23_1988","Fire_25_1988","Fire_26_1988","Fire_28_1988","Fire_29_1988","Fire_31_1988","Fire_32_1989","Fire_33_1989","Fire_35_1989","Fire_38_1989","Fire_41_1989","Fire_42_1989","Fire_48_1990","Fire_49_1991","Fire_50_1991","Fire_51_1991","Fire_1_1988","Fire_2_1988","Fire_3_1988")
fire_list_large <- c("Fire_1_1988","Fire_2_1988","Fire_3_1988")
fire_list_small <- fire_list[! fire_list %in% fire_list_large]

# import high-severity patches
patches <- st_read("data/patches/highsev_patches.shp") %>% 
  mutate(Patch_ID = str_c(Fire_ID,"-",1:n())) %>% 
  st_transform(crs = "EPSG:4326")

# set crs 
crs <- crs(patches)
```

## Calculate Landscape Patterns

### Calculate LEI for Each Patch's Growth

```{r message=TRUE, warning=FALSE}
get_simplelei <- function(fire_name){
  # print patch ID 
  print(fire_name)
  
  # filter to this specific patch
  patches_fire <- patches %>% 
    dplyr::filter(Fire_ID == fire_name)

  # import and name rasters for that fire
  rast_list <- list.files(path = "data/prediction_rasters", pattern = str_c(fire_name,"_rf"), all.files=TRUE, full.names=TRUE)
  rast_names <- str_sub(rast_list,start = -6, end = -5)  
  rast_fire <- rast(rast_list)
  names(rast_fire) <- rast_names
    
  # exclude t0 (no previous timestep to compare to)
  loop_names <- rast_names[2:10]
  
  # choose function to be performed based on fire size
  lei_fullset <- if(fire_name %in% fire_list_small){
    lapply(loop_names,
           get_timesteps_small,
           rast_fire=rast_fire,patches_fire=patches_fire)
  } else{
    lapply(loop_names,
           get_timesteps_large,
           rast_fire=rast_fire,patches_fire=patches_fire)    
  }
  
  lei_df <- do.call(rbind,lei_fullset)
  
  return(lei_df)
}
```

### Function to Handle LEI in Small Patches

```{r}
# function to create LEI dataset for each fire's time steps
get_timesteps_small <- function(rast_name,rast_fire,patches_fire){
  print(rast_name)
  
  # select the timepoint and corresponding raster
  timepoint2 <- rast_name
  timepoint2_raster <- rast_fire[[timepoint2]]  %>% 
      as.factor() 
  
    # set up raster for the previous timepoint
  timepoint1 <- str_c("t",as.numeric(str_sub(timepoint2,2,2))-1)
  timepoint1_raster <- rast_fire[[timepoint1]]  %>% 
    as.factor() 

  # set area outside of patches to presence
  timepoint1_raster[is.na(timepoint1_raster)] <- 2
  
  # difference the two time points to identify areas of change
  timepoint_difference_raster <- timepoint2_raster - timepoint1_raster 

  # convert areas of new presence to polgyons
  timepoint_difference_polys <- as.polygons(timepoint_difference_raster) %>%
    st_as_sf() %>%
    st_cast("POLYGON") %>% 
    dplyr::filter(.[[1]] == 1) %>% 
      st_transform(crs=crs)%>%
      st_join(.,st_make_valid(patches_fire),largest=TRUE)
  
  # control for possibility of no new growth
  if(nrow(timepoint_difference_polys)==0){
    print("no polys")
    columns <- c("count",	"lei",	"Patch_ID",	"lei_category",	"timepoint")
    lei_df <- data.frame(matrix(nrow=0,ncol=length(columns)))
    colnames(lei_df) = columns
    return(lei_df)
  }else{
    val = 0
    lei_poly_df<- list()
    for(i in unique(timepoint_difference_polys$Patch_ID)){
      val = val + 1
      print(str_c(100*round(val/length(unique(timepoint_difference_polys$Patch_ID)),2),"%"))
      
      # get polygon of new growth area for each patch
      patch <- patches_fire %>% 
        dplyr::filter(Patch_ID ==i)
      newgrowth_patch <- timepoint_difference_polys %>% 
        dplyr::filter(Patch_ID == i) %>% 
        summarize(geometry= st_union(geometry))
      
      # buffer to desire lei considered difference, get ring by taking difference
      newgrowth_buffer <- st_as_sf(buffer(vect(newgrowth_patch),100)) %>%
        summarize(geometry = st_union(geometry))
      newgrowth_ring <- st_difference(newgrowth_buffer,newgrowth_patch)
      
      # mask previous timepoints raster to the ring polygon to see previous timestep conifer composition
      raster_ring <- mask(timepoint1_raster,newgrowth_ring)
      freq_df <- freq(raster_ring) %>% 
        mutate(lei = count/sum(count),
               Patch_ID = i)
      lei_poly_df[[i]] <- freq_df
    }
    
    # clean, combine
    lei_df <- do.call(rbind,lei_poly_df)  %>% 
        dplyr::filter(value ==2) %>% 
        dplyr::select(-layer,-value) %>% 
        mutate(lei_category = case_when(lei > 0.5 ~ "infill",
                                        lei < .01 ~ "leapfrog",
                                        TRUE ~ "expansion"),
               timepoint = rast_name)
    
    # export to csv
    write_csv(lei_df,str_c("data/lei_simple/",fire_name,"-",rast_name,".csv"))
  }
} 
```

### Function to Handle LEI in Large Patches

```{r}
# function to create LEI dataset for each fire's time steps
get_timesteps_large <- function(rast_name,rast_fire,patches_fire){
  print(rast_name)
  
  # select the timepoint and corresponding raster
  timepoint2 <- rast_name
  timepoint2_raster <- rast_fire[[timepoint2]]  %>% 
      as.factor() 
  
  # set up raster for the previous timepoint
  timepoint1 <- str_c("t",as.numeric(str_sub(timepoint2,2,2))-1)
  timepoint1_raster <- rast_fire[[timepoint1]]  %>% 
    as.factor() 

  # set area outside of patches to presence
  timepoint1_raster[is.na(timepoint1_raster)] <- 2
  
  # difference the two time points to identify areas of change
  timepoint_difference_raster <- timepoint2_raster - timepoint1_raster 

  # convert areas of new presence to polgyons
  timepoint_difference_polys <- as.polygons(timepoint_difference_raster) %>%
    st_as_sf() %>%
    st_cast("POLYGON") %>% 
    dplyr::filter(.[[1]] == 1) %>% 
    st_transform(crs=crs) %>% 
    st_join(.,patches_fire)

  lei_df<- data.frame()
  
  # control for possibility of no new growth
  if(nrow(timepoint_difference_polys)==0){
    print("no polys")
  } else {
    for(i in str_sort(unique(timepoint_difference_polys$Patch_ID))){
      print(i)
      
      # get polygon of new growth area for each patch
      patch <- patches_fire %>% 
        dplyr::filter(Patch_ID ==i)
      newgrowth_patch <- timepoint_difference_polys %>% 
        dplyr::filter(Patch_ID == i) %>% 
        summarize(geometry= st_union(geometry))
      
      # buffer to desire lei considered difference, get ring by taking difference
      newgrowth_buffer <- st_as_sf(buffer(vect(newgrowth_patch),100)) %>%
        summarize(geometry = st_union(geometry))
      newgrowth_ring <- st_difference(newgrowth_buffer,newgrowth_patch)
      
      # mask previous timepoints raster to the ring polygon to see previous timestep conifer composition
      raster_ring <- mask(timepoint1_raster,newgrowth_ring)
      freq_df <- freq(raster_ring) %>% 
        mutate(lei = count/sum(count),
               Patch_ID = i)%>% 
        dplyr::filter(value ==2) %>% 
        dplyr::select(-layer,-value)%>% 
        mutate(lei_category = case_when(lei > 0.5 ~ "infill",
                                        lei < .01 ~ "leapfrog",
                                        TRUE ~ "expansion"),
               timepoint = rast_name)
      
      lei_df <- rbind(lei_df,freq_df)
    }
    
    # export to csv
    write_csv(lei_df,str_c("data/lei_simple/",fire_name,"-",rast_name,".csv"))
  }
} 
```

### Apply Functions Across All Fires

```{r message=FALSE, warning=FALSE,eval = FALSE}
# map get_lei function to all fires and export simple patchwise lei data 
map(fire_list,get_simplelei)
```


## Analyze Patch-wise LEI

### Combine and Clean Data

```{r message=FALSE, warning=FALSE}
# import all patchwise lei csv files
lei_simple_df <-do.call(bind_rows,lapply(list.files(path = "data/lei_simple", pattern = "Fire", all.files=TRUE, full.names=TRUE),read_csv))

patches_df <- patches %>% 
  mutate(perim_m = as.numeric(round(st_length(st_cast(geometry,to = "MULTILINESTRING")),2)),
         edge_perim_rat = ptch_r_/perim_m,
         perim_rat_cat = case_when(edge_perim_rat > .004 ~ "high edge",
                                   TRUE ~ "low edge")) 

lei_simple_summary <- lei_simple_df %>% 
  left_join(patches_df) %>% 
  filter(ptch_fr %in% c("Douglas-Fir","Fir-Spruce","Lodegepole Pine")) %>% 
  mutate(time_yr = case_when(timepoint == "t0" ~ 2,
                              timepoint == "t1" ~ 5,
                              timepoint == "t2" ~ 8,
                              timepoint == "t3" ~ 11,
                              timepoint == "t4" ~ 14,
                              timepoint == "t5" ~ 17,
                              timepoint == "t6" ~ 20,
                              timepoint == "t7" ~ 23,
                              timepoint == "t8" ~ 26,
                              timepoint == "t9" ~ 29))
```

### Plot

```{r message=FALSE, warning=FALSE}
ggplot(lei_simple_summary,aes(x=as.factor(time_yr),y=lei,fill=ptch_fr)) + 
  geom_boxplot(outlier.shape = NA) +
  labs(fill = "Forest Type",x = "Years Post-Fire",y="LEI",title = "LEI Over Time for Each Forest Type")+
  theme_classic()
```

