# Landscape Expansion

## Set Up

### Import Libraries

```{r libraries 10, message=FALSE, warning=FALSE}
library(sf)
library(terra)
library(mapview)
library(raster)
library(tidyverse)
library(ggplot2) 
library(landscapemetrics)
```

### Import Patch Polygons

```{r import patch4, message=FALSE, warning=FALSE}
# fire list
fire_list <- c("Fire_54_1991","Fire_4_1988","Fire_7_1988","Fire_9_1988","Fire_10_1988","Fire_11_1988","Fire_12_1988","Fire_13_1988","Fire_14_1988","Fire_15_1988","Fire_16_1988","Fire_18_1988","Fire_19_1988","Fire_20_1988","Fire_22_1988","Fire_23_1988","Fire_25_1988","Fire_26_1988","Fire_28_1988","Fire_29_1988","Fire_31_1988","Fire_32_1989","Fire_33_1989","Fire_35_1989","Fire_38_1989","Fire_41_1989","Fire_42_1989","Fire_48_1990","Fire_49_1991","Fire_50_1991","Fire_51_1991","Fire_1_1988","Fire_2_1988","Fire_3_1988")

# import high-severity patches
patches <- st_read("data/patches/highsev_patches.shp") %>% 
  mutate(Patch_ID = str_c(Fire_ID,"-",1:n())) %>% 
  st_transform(crs = "EPSG:4326")

# set crs 
crs <- crs(patches)

# import fire polygons
fires_export <- st_read("data/fire_boundaries/fires_export.shp") %>% 
  st_transform(crs = crs)
```

## Calculate Landscape Patterns

```{r message=TRUE, warning=FALSE}
fire_name <- "Fire_1_1988"

get_lei <- function(fire_name,fires_export){
  # print patch ID 
  print(fire_name)
  
  # filter to this specific patch
  patches_fire <- patches %>% 
    filter(Fire_ID == fire_name)

  # import and name rasters for that fire
  rast_list <- list.files(path = "data/prediction_rasters", pattern = str_c(fire_name,"_rf"), all.files=TRUE, full.names=TRUE)
  rast_names <- str_sub(rast_list,start = -6, end = -5)  
  rast_fire <- rast(rast_list)
  names(rast_fire) <- rast_names
  
  lei_fullset <- lapply(rast_names,
                        get_timesteps,
                        rast_fire=rast_fire,patches_fire=patches_fire)
  
  lei_df <- do.call(rbind,lei_fullset)
  
  return(lei_df)
}
```

```{r message=FALSE, warning=FALSE}
# rast_name <- "t2"

# function to create LEI dataset for each fire's time steps
get_timesteps <- function(rast_name,rast_fire,patches_fire){
  print(rast_name)
  
  # select the timepoint and corresponding raster
  timepoint <- rast_name
  timepoint_raster <- rast_fire[[timepoint]]  %>% 
      as.factor() %>% 
      terra::project(.,"EPSG: 3857")
  
 
    lsm_patches_df <- list()
    for(i in unique(patches_fire$Patch_ID)){
      print(i)
      patch <- patches_fire %>% 
        filter(Patch_ID==i)%>% 
        st_transform(crs = "EPSG: 3857")
      masked_rast <- mask(timepoint_raster,patch)
      
      if(all(is.na(values(masked_rast))) == FALSE){
        patch_lsm <- calculate_lsm(masked_rast, 
                                       what = c("lsm_c_clumpy","lsm_c_ai","lsm_c_enn_mn","lsm_c_cohesion",
                                                 "lsm_c_pland","lsm_c_np","lsm_c_ca",
                                                 "lsm_c_area_mn","lsm_l_contag","lsm_c_ca"), 
                                   count_boundary=TRUE,
                                   consider_boundary = TRUE,
                                   edge_depth = 5) %>% 
          filter(class ==2) %>% 
          mutate(Patch_ID = i,
                 timepoint = rast_name,
                 ptch_fr=patch$ptch_fr) %>% 
          select(-layer,-level,-class,-id)
        lsm_patches_df[[i]] <- patch_lsm
        } else {
          lsm_patches_df[[i]] <- data.frame(row.names = c("empty"))
        }
    }
  lsm_df <- do.call(rbind,lsm_patches_df)
  
  write_csv(lsm_df,str_c("data/lsm/",i,".csv"))
} 
```

```{r message=FALSE, warning=FALSE}
fire_list <- c("Fire_54_1991","Fire_4_1988","Fire_7_1988","Fire_9_1988","Fire_10_1988","Fire_11_1988","Fire_12_1988","Fire_13_1988","Fire_14_1988","Fire_15_1988","Fire_16_1988","Fire_18_1988","Fire_19_1988","Fire_20_1988","Fire_22_1988","Fire_23_1988","Fire_25_1988","Fire_26_1988","Fire_28_1988","Fire_29_1988","Fire_31_1988","Fire_32_1989","Fire_33_1989","Fire_35_1989","Fire_38_1989","Fire_41_1989","Fire_42_1989","Fire_48_1990","Fire_49_1991","Fire_50_1991","Fire_51_1991","Fire_1_1988","Fire_2_1988","Fire_3_1988")


for(i in fire_list){
  lei_fulldataset <- get_lei(i,fires_export)
  write_csv(lei_fulldataset,str_c("data/lsm/",i,".csv"))
}
```















