# Edge Encroachment

## Set Up

### Import Libraries

```{r libraries 10, message=FALSE, warning=FALSE}
library(sf)
library(terra)
library(mapview)
library(raster)
library(tidyverse)
library(ggplot2) 
library(cowplot)
```

```{r}
# import high-severity patches
patches_df <- st_read("data/patches/highsev_patches.shp") %>% 
  mutate(Patch_ID = str_c(Fire_ID,"-",1:n())) %>% 
  st_transform(crs = "EPSG:4326") %>% 
  st_drop_geometry()

types <- c("Douglas-Fir","Fir-Spruce","Lodegepole Pine")
# large_patch_df <- patches_df %>% 
#   filter(ptch_r_ >100,
#          ptch_fr %in% types)
```


```{r message=FALSE, warning=FALSE}
dist_df <- do.call(bind_rows,lapply(list.files(path = "data/edge_distance", pattern = "Fire", all.files=TRUE, full.names=TRUE),read_csv))

lei_df <- do.call(bind_rows,lapply(list.files(path = "data/lei", pattern = "Fire", all.files=TRUE, full.names=TRUE),read_csv))

lei_simple_df <-do.call(bind_rows,lapply(list.files(path = "data/lei_simple", pattern = "Fire", all.files=TRUE, full.names=TRUE),read_csv))
  
lsm_df <- do.call(bind_rows,lapply(list.files(path = "data/lsm", pattern = "Fire", all.files=TRUE, full.names=TRUE),read_csv))


```

## LEI 
```{r}
lei_summary <- lei_df %>% 
  select(-geometry,-value)%>% 
  filter(ptch_fr %in% c("Douglas-Fir","Fir-Spruce","Lodegepole Pine"))%>% 
  group_by(lei_category,ptch_fr,timepoint)%>% 
  summarize(n=n(),
            area=sum(newgrowth_area_ha)) %>% 
  ungroup() %>% 
  group_by(ptch_fr,timepoint) %>% 
  mutate(tot_area =sum(area),
         perc_area = area/tot_area,
         time_yr = case_when(timepoint == "t0" ~ 2,
                              timepoint == "t1" ~ 5,
                              timepoint == "t2" ~ 8,
                              timepoint == "t3" ~ 11,
                              timepoint == "t4" ~ 14,
                              timepoint == "t5" ~ 17,
                              timepoint == "t6" ~ 20,
                              timepoint == "t7" ~ 23,
                              timepoint == "t8" ~ 26,
                              timepoint == "t9" ~ 29))

ggplot(lei_summary,aes(time_yr,perc_area,color= ptch_fr,group=ptch_fr))+
  geom_point()+
  geom_smooth(se = FALSE,method = "loess")+
  facet_wrap(~lei_category, scales = "free_y")+ 
  labs(title = "Area of New Growth for Each Expansion Type",color = "Forest Type",
       y = "Percent of New Growth",x="Years Post-Fire")+
  theme_classic()

ggplot(lei_summary,aes(time_yr,perc_area,fill= lei_category,group=lei_category))+
  geom_col() +
  facet_wrap(~ptch_fr, scales = "free_y")+ 
  labs(title = "Area of New Growth for Each Expansion Type",
       fill = "Forest Type",
       y = "Percent of New Growth",x="Years Post-Fire")+
  theme_classic()
```


```{r}
lei_simple_summary <- lei_simple_df %>% 
  left_join(patches_df) %>% 
  filter(ptch_fr %in% c("Douglas-Fir","Fir-Spruce","Lodegepole Pine")) %>% 
  mutate(time_yr = case_when(timepoint == "t0" ~ 2,
                              timepoint == "t1" ~ 5,
                              timepoint == "t2" ~ 8,
                              timepoint == "t3" ~ 11,
                              timepoint == "t4" ~ 14,
                              timepoint == "t5" ~ 17,
                              timepoint == "t6" ~ 20,
                              timepoint == "t7" ~ 23,
                              timepoint == "t8" ~ 26,
                              timepoint == "t9" ~ 29))

ggplot(lei_simple_summary,aes(x=as.factor(time_yr),y=lei,fill=ptch_fr)) + 
  geom_boxplot(outlier.shape = NA) +
  # geom_line(data= lei_simple_summary %>% 
  #             group_by(ptch_fr,time_yr) %>% 
  #             summarize(lei=mean(lei)),
  #           aes(x=as.factor(time_yr),y=lei,color = ptch_fr,group = ptch_fr),size = 1) +
  labs(fill = "Forest Type",x = "Years Post-Fire",title = "LEI Over Time for Each Forest Type")+
  theme_classic()
```

## Distances

### Of All Growth
```{r message=FALSE, warning=FALSE}
types <- c("Lodegepole Pine","Douglas-Fir","Fir-Spruce")

dist_summary_all <- dist_df %>% 
  filter(growth_type=="all growth") %>% 
  left_join(.,patches_df,by="Patch_ID") %>% 
  filter(ptch_fr %in%  types) %>% 
  group_by(ptch_fr,timepoint,edge_dist_m) %>% 
  summarize(count = sum(count))

ggplot(dist_summary_all,aes(edge_dist_m,weight=count,fill=ptch_fr))+
  geom_density(alpha = 0.2)
  
  geom_histogram(bins =6,position ="dodge")+
  facet_wrap(~timepoint) +
  labs(title = "Distance of Growth from Patch Edge")

```

### Of New Growth
```{r message=FALSE, warning=FALSE}
dist_summary_new <- dist_df %>% 
  filter(growth_type=="new growth") %>% 
  left_join(.,patches_df,by="Patch_ID") %>% 
  filter( ptch_fr %in%  types) %>% 
  group_by(ptch_fr,timepoint,edge_dist_m) %>% 
  summarize(count = sum(count))

# ggplot(dist_summary_new,aes(edge_dist_m,weight=count,fill=ptch_fr))+
#   geom_histogram(bins =6,position ="dodge")+
#   facet_wrap(~timepoint)+
#   labs(title = "Distance of New Growth from Patch Edge")

plot1 <- ggplot(dist_summary_new %>% filter(ptch_fr=="Lodegepole Pine"),aes(edge_dist_m,weight=count))+
  geom_histogram(bins =17)+
  facet_grid(~timepoint) +
  theme(axis.text.x = element_text(angle = 90))
plot2 <- ggplot(dist_summary_new %>% filter(ptch_fr=="Douglas-Fir"),aes(edge_dist_m,weight=count))+
  geom_histogram(bins =17)+
  facet_grid(~timepoint) +
  theme(axis.text.x = element_text(angle = 90))
plot3 <- ggplot(dist_summary_new %>% filter(ptch_fr=="Fir-Spruce"),aes(edge_dist_m,weight=count))+
  geom_histogram(bins =17)+
  facet_grid(~timepoint) +
  theme(axis.text.x = element_text(angle = 90))

plot_grid(plot1,plot2,plot3,labels=types,ncol=1)
```

## Landscape Metrics

```{r}
lsm_summary_nn <- lsm_df %>% 
  filter(metric == "enn_mn",
         ptch_fr %in% types,
         timepoint != "t0") %>% 
  group_by(ptch_fr,timepoint) %>% 
  summarize(nn= mean(value,na.rm=TRUE))

ggplot(lsm_summary_nn,aes(timepoint,nn,color = ptch_fr,group=ptch_fr))+
  geom_line()+
  labs(title = "Nearest Neighbor Distances of Conifer Regrowth")

lsm_summary_pland <- lsm_df %>% 
  filter(metric == "pland",
         ptch_fr %in% types,
         timepoint != "t0") %>% 
  group_by(ptch_fr,timepoint) %>% 
  summarize(pland= mean(value,na.rm=TRUE)) 

ggplot(lsm_summary_pland,aes(timepoint,pland,color = ptch_fr,group=ptch_fr))+
  geom_line() +
  labs(title = "Percent of Land Area Occupied by Conifers")

```

