--- 
title: "Post-Fire Conifer Regeneration"
author: "Casey Menick"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
description: 
output: html_document
link-citations: yes
github-repo: rstudio/bookdown-demo
always_allow_html: true
---

# About

There has been an increasing number of large, high-severity wildfires across the Western United States. It is not fully understood how this intensification may impact conifer forests of the West, whose resilience is dependent on successful seedling regeneration. It is important to understand how these conifer-dominated forests are able to recolonize high-severity burn patches and subsequently respond to these shifting disturbance regimes. The goal of this research is to characterize patterns of conifer recolonization within high-severity burn patches over a 30-year study period. We investigated 34 high-severity wildfire complexes that occurred between 1988 and 1991 in conifer-dominated ecosystems of the northern Rocky Mountains. Composite snow-cover Landsat imagery was utilized to isolate conifer-specific vegetation by diminishing spectral contributions from deciduous vegetation. Conifer regeneration was determined to be detectable by Landsat approximately 11-19 years post-fire and at >10% canopy cover using these methods. The trajectory of snow-cover Landsat NDVI was utilized to estimate recovery time to pre-fire conifer vegetation for lodgepole pine (29.5 years), Douglas-fir (36.9 years), and fir-spruce forest (48.7 years). The presence of conifer regeneration was then modeled at 3-year intervals post-fire to characterize the progression of recolonization. Conifer reoccupancy analysis showed that 65% of the total high-severity burn area was reforested after 30 years. Across all high-severity patches, median patch reoccupancy was 100% within lodgepole pine, 91.1% within Douglas-fir, and 41.3% within fir-spruce. While we identified overall patterns of conifer resilience, we identified lower probabilities of 30-year conifer recovery within low-edge patches, drier climates, and fir-spruce forests. These findings have implications for potential reduced resilience due to climate change and may be applied to support forest restoration decision-making following high-severity wildfire. Additional future analyses should be conducted using snow-cover remote sensing imagery to identify patterns of post-disturbance conifer recovery over a wider spatial and temporal extent.


```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
